name: CI/CD Workflow

on:
  push:
    types:
      - closed
    branches:
      - master

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: git config --global user.email "actions@github.com" && git config --global user.name "GitHub Actions"

    - name: Determine version
      id: determine_version
      run: echo "::set-output name=version::$(bash determine_version.sh)"  # Replace with the script or command to determine version

    - name: Create tag
      run: |
        version="${{ steps.determine_version.outputs.version }}"
        git tag -a "v${version}" -m "Version ${version}"
        git push origin "v${version}"

    - name: Create release
      run: |
        gh release create "v${{ steps.determine_version.outputs.version }}" -t "Release v${{ steps.determine_version.outputs.version }}" -n "Release notes for v${{ steps.determine_version.outputs.version }}"

    - name: Get previous tag
      id: get_prev_tag
      run: echo "::set-output name=prev_tag::$(git describe --tags --abbrev=0 HEAD^)"

    - name: Create release note from comparison
      run: |
        previous_tag="${{ steps.get_prev_tag.outputs.prev_tag }}"
        current_tag="v${{ steps.determine_version.outputs.version }}"
        gh release create "${current_tag}" $(git log --pretty=format:'- [%h] %s (%an)' "${previous_tag}".."${current_tag}")
