name: CI/CD Workflow

on:
  pull_request:
    types:
      - closed

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Git
      run: git config --global user.email "actions@github.com" && git config --global user.name "GitHub Actions"

    - name: Get version from package.json
      id: get_version
      run: echo "::set-output name=version::$(jq -r '.version' package.json)"

    - name: Create tag
      run: |
        version="${{ steps.get_version.outputs.version }}"
        git tag -a "v${version}" -m "Version ${version}"
        git push origin "v${version}"

    - name: Create release
      run: |
        gh release create "v${{ steps.get_version.outputs.version }}" -t "Release v${{ steps.get_version.outputs.version }}" -n "Release notes for v${{ steps.get_version.outputs.version }}"

    - name: Get previous tag
      id: get_prev_tag
      run: echo "::set-output name=prev_tag::$(git describe --tags --abbrev=0 HEAD^)"

    - name: Create release note from comparison
      run: |
        previous_tag="${{ steps.get_prev_tag.outputs.prev_tag }}"
        current_tag="v${{ steps.get_version.outputs.version }}"
        gh release create "${current_tag}" $(git log --pretty=format:'- [%h] %s (%an)' "${previous_tag}".."${current_tag}")
